debug: false

logger.level:
  io.pivotal.dmfrey: DEBUG

server:
  port: ${PORT:9080}
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false


---
spring:
  profiles: event-store

  cloud:
    stream:
      bindings:
        input:
          binder: rabbitmq
          destination: board-events
          group: command-board-events-group
          consumer:
            useNativeDecoding: true
            headerMode: raw
      kafka:
        streams:
          binder:
            brokers: localhost
            zkNodes: localhost

---
spring:
  profiles: kafka

  cloud:
    stream:
      bindings:
        output:
          binder: kafka
          destination: board-events
          contentType: application/json
          producer:
            headerMode: raw # Outbound data has no embedded headers
        input:
          destination: board-events
          contentType: application/json
          group: command-board-events-group
          consumer:
            useNativeDecoding: true
            headerMode: raw
      kafka:
        streams:
          binder:
            brokers: localhost
            zkNodes: localhost

logger.level:
  org.apache.kafka: DEBUG
  org.apache.kafka.clients: ERROR